#!/usr/bin/env python3
"""Patch 89 — Fix SWING scanner to use full Kraken 4h OHLC technicals

Problem: _perp_signal_scan_loop sends bare-bones signals {symbol, side, regime_label}
with no technical indicators. ML predictor defaults to momentum_5m=0, rsi=50 etc.
→ always predicts negative return → EV = -PERP_STOP_PCT% → EV_FILTER blocks everything.

Fix: Replace CoinGecko 24h-change hack with Kraken 4h OHLC (interval=240), same
pattern as SCALP (5m) and MID (15m) scanners. Compute RSI/MACD/ATR/volume and pass
full feature dict so the ML can make a real prediction.

All existing gates (EV filter, regime guard, daily cap, SWING_ONLY lock) unchanged.
"""
from pathlib import Path
import subprocess

MAIN = Path("/root/memecoin_engine/dashboard/backend/main.py")
text = MAIN.read_text()

# ─────────────────────────────────────────────────────────────────────────────
# Anchor: the old CoinGecko-based SWING scanner body (from _CG_IDS through
# the closing log.debug of the outer except)
# ─────────────────────────────────────────────────────────────────────────────
OLD = (
    '    # CoinGecko IDs for each symbol\n'
    '    _CG_IDS = {\n'
    '        "SOL": "solana", "BTC": "bitcoin", "ETH": "ethereum",\n'
    '        "SUI":  "sui",\n'
    '        "TON":  "the-open-network",\n'
    '        "AVAX": "avalanche-2",\n'
    '        "ARB":  "arbitrum",\n'
    '        "OP":   "optimism",\n'
    '        "NEAR": "near",\n'
    '        "INJ":  "injective-protocol",\n'
    '        "SEI":  "sei-network",\n'
    '        "APT":  "aptos",\n'
    '    }\n'
    '\n'
    '    while True:\n'
    '        await asyncio.sleep(120)  # 2 min — more data, faster learning\n'
    '        try:\n'
    '            perp_enabled = os.getenv("PERP_EXECUTOR_ENABLED", "false").lower() == "true"\n'
    '            if not perp_enabled:\n'
    '                continue\n'
    '\n'
    '            # Configurable 1h change threshold (default 0.3% for paper — very sensitive)\n'
    '            try:\n'
    '                threshold = float(os.getenv("PERP_1H_THRESHOLD", "0.3"))\n'
    '            except Exception:\n'
    '                threshold = 0.3\n'
    '\n'
    '            # Fetch BTC + ETH + SOL prices + 24h change in one request\n'
    '            import requests as _req\n'
    '            try:\n'
    '                ids = ",".join(_CG_IDS.values())\n'
    '                r = _req.get(\n'
    '                    f"https://api.coingecko.com/api/v3/simple/price"\n'
    '                    f"?ids={ids}&vs_currencies=usd&include_24hr_change=true",\n'
    '                    timeout=8,\n'
    '                )\n'
    '                price_data = r.json()\n'
    '            except Exception as fe:\n'
    '                log.debug("perp_scan price fetch error: %s", fe)\n'
    '                continue\n'
    '\n'
    '            # Get current regime\n'
    '            try:\n'
    '                from utils.market_cycle import get_cycle_phase  # type: ignore\n'
    '                phase = get_cycle_phase()\n'
    '            except Exception:\n'
    '                phase = "TRANSITION"\n'
    '\n'
    '            from utils.perp_executor import execute_perp_signal  # type: ignore\n'
    '\n'
    '            # Scan all three assets\n'
    '            for symbol, cg_id in _CG_IDS.items():\n'
    '                try:\n'
    '                    asset = price_data.get(cg_id, {})\n'
    '                    chg_24h = float(asset.get("usd_24h_change", 0))\n'
    '                    chg_1h  = chg_24h / 6.0  # rough 1h proxy from 24h\n'
    '\n'
    '                    # LONG signal: price moving up + regime not BEAR\n'
    '                    if chg_1h > threshold and phase != "BEAR":\n'
    '                        regime_label = phase if phase else "BULL"\n'
    '                        await execute_perp_signal({\n'
    '                            "symbol": symbol, "side": "LONG",\n'
    '                            "regime_label": regime_label, "source": "auto_scan",\n'
    '                        })\n'
    '                        log.info(\n'
    '                            "[PERP SCAN] LONG %s  phase=%s  1h=+%.2f%%  threshold=%.1f%%",\n'
    '                            symbol, phase, chg_1h, threshold,\n'
    '                        )\n'
    '\n'
    '                    # SHORT signal: price moving down + regime not BULL\n'
    '                    elif chg_1h < -threshold and phase != "BULL":\n'
    '                        regime_label = phase if phase else "BEAR"\n'
    '                        await execute_perp_signal({\n'
    '                            "symbol": symbol, "side": "SHORT",\n'
    '                            "regime_label": regime_label, "source": "auto_scan",\n'
    '                        })\n'
    '                        log.info(\n'
    '                            "[PERP SCAN] SHORT %s  phase=%s  1h=%.2f%%  threshold=%.1f%%",\n'
    '                            symbol, phase, chg_1h, threshold,\n'
    '                        )\n'
    '\n'
    '                except Exception as sym_e:\n'
    '                    log.debug("perp_scan %s error: %s", symbol, sym_e)\n'
    '\n'
    '        except Exception as _e:\n'
    '            log.debug("perp_signal_scan error: %s", _e)\n'
)
assert text.count(OLD) == 1, f"89: expected 1 anchor, found {text.count(OLD)}"

NEW = (
    '    # Patch 89: Kraken pair map — same as SCALP/MID scanners\n'
    '    _KRAKEN_PAIRS = {\n'
    '        "SOL": ("SOLUSD",  "SOLUSD"),\n'
    '        "BTC": ("XBTUSD",  "XXBTZUSD"),\n'
    '        "ETH": ("ETHUSD",  "XETHZUSD"),\n'
    '        "SUI":  ("SUIUSD",  "SUIUSD"),\n'
    '        "TON":  ("TONUSD",  "TONUSD"),\n'
    '        "AVAX": ("AVAXUSD", "AVAXUSD"),\n'
    '        "ARB":  ("ARBUSD",  "ARBUSD"),\n'
    '        "OP":   ("OPUSD",   "OPUSD"),\n'
    '        "NEAR": ("NEARUSD", "NEARUSD"),\n'
    '        "INJ":  ("INJUSD",  "INJUSD"),\n'
    '        "SEI":  ("SEIUSD",  "SEIUSD"),\n'
    '        "APT":  ("APTUSD",  "APTUSD"),\n'
    '    }\n'
    '\n'
    '    while True:\n'
    '        await asyncio.sleep(120)  # 2 min\n'
    '        try:\n'
    '            perp_enabled = os.getenv("PERP_EXECUTOR_ENABLED", "false").lower() == "true"\n'
    '            if not perp_enabled:\n'
    '                continue\n'
    '\n'
    '            # 4h threshold — 0.5% default (larger move on 4h candle vs 5m/15m)\n'
    '            try:\n'
    '                threshold = float(os.getenv("SWING_4H_THRESHOLD", "0.5"))\n'
    '            except Exception:\n'
    '                threshold = 0.5\n'
    '\n'
    '            import requests as _req\n'
    '\n'
    '            try:\n'
    '                from utils.market_cycle import get_cycle_phase  # type: ignore\n'
    '                phase = get_cycle_phase()\n'
    '            except Exception:\n'
    '                phase = "TRANSITION"\n'
    '\n'
    '            from utils.perp_executor import execute_perp_signal  # type: ignore\n'
    '\n'
    '            for symbol, (kraken_pair, result_key) in _KRAKEN_PAIRS.items():\n'
    '                try:\n'
    '                    # Fetch 4-hour OHLC candles from Kraken (no API key required)\n'
    '                    r = _req.get(\n'
    '                        f"https://api.kraken.com/0/public/OHLC?pair={kraken_pair}&interval=240",\n'
    '                        timeout=8,\n'
    '                    )\n'
    '                    data = r.json()\n'
    '                    errors = data.get("error", [])\n'
    '                    if errors:\n'
    '                        log.warning("[SWING SCAN] Kraken error for %s: %s", symbol, errors)\n'
    '                        continue\n'
    '\n'
    '                    candles = data.get("result", {}).get(result_key, [])\n'
    '                    if len(candles) < 3:\n'
    '                        log.debug("[SWING SCAN] not enough candles for %s (%d)", symbol, len(candles))\n'
    '                        continue\n'
    '\n'
    '                    prev_close = float(candles[-3][4])\n'
    '                    curr_close = float(candles[-2][4])\n'
    '                    price_now  = float(candles[-2][4])\n'
    '\n'
    '                    if prev_close <= 0:\n'
    '                        continue\n'
    '\n'
    '                    chg_4h = (curr_close - prev_close) / prev_close * 100\n'
    '\n'
    '                    rsi       = _compute_rsi(candles)\n'
    '                    macd      = _compute_macd(candles)\n'
    '                    atr       = _compute_atr(candles)\n'
    '                    macd_hist = macd["histogram"] if macd else None\n'
    '                    macd_cross = macd["crossover"] if macd else None\n'
    '\n'
    '                    log.info(\n'
    '                        "[SWING SCAN] %s  4h=%.3f%%  RSI=%s  MACD_H=%s  ATR=%s%%  cross=%s",\n'
    '                        symbol, chg_4h, rsi, macd_hist, atr, macd_cross,\n'
    '                    )\n'
    '\n'
    '                    # ── Volume filter (same threshold as SCALP/MID) ──\n'
    '                    _volumes = [float(c[6]) for c in candles[-22:-1]] if len(candles) >= 22 else [float(c[6]) for c in candles[:-1]]\n'
    '                    _avg_vol  = sum(_volumes) / len(_volumes) if _volumes else 0\n'
    '                    _curr_vol = float(candles[-2][6])\n'
    '                    _vol_ratio = round(_curr_vol / _avg_vol, 2) if _avg_vol > 0 else 0\n'
    '                    if _avg_vol > 0 and _curr_vol < _avg_vol * 1.5:\n'
    '                        log.debug("[SWING] %s SKIP vol %.1f < 1.5x avg %.1f (r=%.2f)", symbol, _curr_vol, _avg_vol, _vol_ratio)\n'
    '                        continue\n'
    '\n'
    '                    # ── Dip-buy detection on 4h timeframe (32h trend window) ──\n'
    '                    _signal_source = "swing"\n'
    '                    _dip_buy_long  = False\n'
    '                    _dip_buy_short = False\n'
    '                    if len(candles) >= 16:\n'
    '                        _older_avg  = sum(float(c[4]) for c in candles[-16:-8]) / 8\n'
    '                        _recent_avg = sum(float(c[4]) for c in candles[-8:-1]) / 7\n'
    '                        _trend_32h  = (_recent_avg - _older_avg) / _older_avg * 100 if _older_avg > 0 else 0\n'
    '                        if _trend_32h > 1.0 and chg_4h < -0.3 and (rsi is None or rsi < 65):\n'
    '                            _dip_buy_long  = True\n'
    '                            _signal_source = "dip_buy"\n'
    '                            log.info("[SWING] %s DIP_BUY LONG 32h=+%.2f%% dip=%.3f%% RSI=%s vol_r=%.1f", symbol, _trend_32h, chg_4h, rsi, _vol_ratio)\n'
    '                        elif _trend_32h < -1.0 and chg_4h > 0.3 and (rsi is None or rsi > 35):\n'
    '                            _dip_buy_short = True\n'
    '                            _signal_source = "dip_buy"\n'
    '                            log.info("[SWING] %s DIP_BUY SHORT 32h=%.2f%% bounce=+%.3f%% RSI=%s vol_r=%.1f", symbol, _trend_32h, chg_4h, rsi, _vol_ratio)\n'
    '\n'
    '                    _sent_score = 0.0\n'
    '                    _sent_boost = 0\n'
    '\n'
    '                    if chg_4h > threshold or _dip_buy_long:\n'
    '                        # ── RSI filter ──\n'
    '                        if rsi is not None and rsi > 75 and not _dip_buy_long:\n'
    '                            log.info("[SWING] %s SKIP LONG: RSI=%.1f overbought", symbol, rsi)\n'
    '                            continue\n'
    '                        # ── MACD filter ──\n'
    '                        if macd_hist is not None and macd_hist < 0 and macd_cross != "BULLISH" and not _dip_buy_long:\n'
    '                            log.info("[SWING] %s SKIP LONG: MACD bearish h=%.4f", symbol, macd_hist)\n'
    '                            continue\n'
    '\n'
    '                        try:\n'
    '                            _ensure_engine_path()\n'
    '                            from utils.x_sentiment import get_sentiment\n'
    '                            _sent = await get_sentiment(symbol)\n'
    '                            _sent_score = _sent.get("sentiment_score", 0)\n'
    '                            _sent_boost = _sent.get("boost", 0)\n'
    '                            if _sent_boost != 0:\n'
    '                                logger.info("[SENTIMENT] %s score=%.2f boost=%+d vol_spike=%s",\n'
    '                                            symbol, _sent_score, _sent_boost, _sent.get("volume_spike"))\n'
    '                        except Exception as _se:\n'
    '                            pass\n'
    '\n'
    '                        await execute_perp_signal({\n'
    '                            "symbol": symbol, "side": "LONG",\n'
    '                            "regime_label": phase or "BULL", "source": _signal_source,\n'
    '                            "sentiment_score": _sent_score,\n'
    '                            "sentiment_boost": _sent_boost,\n'
    '                            "momentum_5m": round(chg_4h, 3),  # 4h chg as ML momentum proxy\n'
    '                            "momentum_4h": round(chg_4h, 3),\n'
    '                            "price_at_signal": price_now,\n'
    '                            "rsi_14": rsi,\n'
    '                            "macd_hist": macd_hist,\n'
    '                            "macd_cross": macd_cross,\n'
    '                            "atr_pct": atr,\n'
    '                            "vol_ratio": _vol_ratio,\n'
    '                        })\n'
    '                        log.info("[SWING] -> LONG %s 4h=%.3f%% RSI=%s MACD=%s src=%s vol=%.1f",\n'
    '                                 symbol, chg_4h, rsi, macd_cross, _signal_source, _vol_ratio)\n'
    '\n'
    '                    elif chg_4h < -threshold or _dip_buy_short:\n'
    '                        # ── RSI filter ──\n'
    '                        if rsi is not None and rsi < 25 and not _dip_buy_short:\n'
    '                            log.info("[SWING] %s SKIP SHORT: RSI=%.1f oversold", symbol, rsi)\n'
    '                            continue\n'
    '                        # ── MACD filter ──\n'
    '                        if macd_hist is not None and macd_hist > 0 and macd_cross != "BEARISH" and not _dip_buy_short:\n'
    '                            log.info("[SWING] %s SKIP SHORT: MACD bullish h=%.4f", symbol, macd_hist)\n'
    '                            continue\n'
    '\n'
    '                        await execute_perp_signal({\n'
    '                            "symbol": symbol, "side": "SHORT",\n'
    '                            "regime_label": phase or "BEAR", "source": _signal_source,\n'
    '                            "sentiment_score": _sent_score,\n'
    '                            "sentiment_boost": _sent_boost,\n'
    '                            "momentum_5m": round(chg_4h, 3),  # 4h chg as ML momentum proxy\n'
    '                            "momentum_4h": round(chg_4h, 3),\n'
    '                            "price_at_signal": price_now,\n'
    '                            "rsi_14": rsi,\n'
    '                            "macd_hist": macd_hist,\n'
    '                            "macd_cross": macd_cross,\n'
    '                            "atr_pct": atr,\n'
    '                            "vol_ratio": _vol_ratio,\n'
    '                        })\n'
    '                        log.info("[SWING] -> SHORT %s 4h=%.3f%% RSI=%s MACD=%s src=%s vol=%.1f",\n'
    '                                 symbol, chg_4h, rsi, macd_cross, _signal_source, _vol_ratio)\n'
    '\n'
    '                except Exception as sym_e:\n'
    '                    log.warning("[SWING SCAN] %s error: %s", symbol, sym_e)\n'
    '\n'
    '        except Exception as _e:\n'
    '            log.debug("perp_signal_scan error: %s", _e)\n'
)

text = text.replace(OLD, NEW)
assert text.count(NEW) == 1, "89: replacement produced multiple matches"
print("89: SWING scanner body replaced ✓")

# ─────────────────────────────────────────────────────────────────────────────
# Also update the docstring to reflect the new implementation
# ─────────────────────────────────────────────────────────────────────────────
OLD_DOC = (
    'async def _perp_signal_scan_loop():\n'
    '    """Background: auto-fire paper perp trades every 2 min on SOL/BTC/ETH.\n'
    '\n'
    '    Paper mode is intentionally aggressive — low threshold, many assets, short cooldown.\n'
    '    Goal: maximum learning data. Tighten thresholds when switching to live.\n'
    '    """'
)
assert text.count(OLD_DOC) == 1, f"89 doc: expected 1, found {text.count(OLD_DOC)}"

NEW_DOC = (
    'async def _perp_signal_scan_loop():\n'
    '    """Background: SWING perp signal scanner — 4h Kraken OHLC, every 2 min.\n'
    '\n'
    '    Patch 89: replaced bare-bones CoinGecko 24h-change signals with full Kraken\n'
    '    4h OHLC technicals (RSI/MACD/ATR/volume/dip-buy) so the ML predictor gets\n'
    '    real features instead of defaults → EV filter can find genuine opportunities.\n'
    '    """'
)
text = text.replace(OLD_DOC, NEW_DOC)
assert text.count(NEW_DOC) == 1, "89 doc replacement error"
print("89: docstring updated ✓")

# ─────────────────────────────────────────────────────────────────────────────
# Write + syntax check
# ─────────────────────────────────────────────────────────────────────────────
MAIN.write_text(text)
r = subprocess.run(["python3", "-m", "py_compile", str(MAIN)], capture_output=True, text=True)
if r.returncode != 0:
    print("COMPILE ERROR:", r.stderr)
    raise SystemExit(1)
print("89: main.py compile OK ✓")
print("\n89 patch complete — restart service to activate")
